### ISSUE TITLE
NFL Scores

### ISSUE THREAD

**Issue by hoveeman** [jclarke0000/MMM-MyScoreboard#66]
Yesterday all of the NCAAF scores showed up and were updating successfully. Today I did not have any NFL scores show up. I imagine the api changed for NFL.

**Comment by sanj926** [comment]
Same problem and I'm getting the error:

[MMM-MyScoreboard] 18-Sep-22 11:29 ** ERROR ** Couldn't retrieve data for provider SNET: Error: getaddrinfo ENOTFOUND d290qmen6zswb.cloudfront.net

**Comment by sanj926** [comment]
this is actually fixed in one of the pull requests!  Just tried it and it works again.

**Comment by hoveeman** [comment]
Hmm, i'm still getting the same error. I even removed the folder in the modules directory and re-installed it. 

`-Sep-22 13:48 ** ERROR ** Couldn't retrieve data for provider SNET: Error: getaddrinfo ENOTFOUND d290qmen6zswb.cloudfront.net d290qmen6zswb.cloudfront.net:443"`

**Comment by sanj926** [comment]
https://github.com/jclarke0000/MMM-MyScoreboard/pull/61/commits/95e04209f42b49fc93b5e0c4e9d0f06429a5b5b0

**Comment by hoveeman** [comment]
Thank you so much! That pull request fixed my issue as well.

**Comment by jclarke0000** [comment]
NFL and NCAAF are pulled from different sources.  NFL from SportsNet, and NCAAF from ESPN.  The SNET provider has been updated with the right url, and is working again.  do a `git pull`.
