### ISSUE TITLE
Module stuck on loading

### ISSUE THREAD

**Issue by athanast6** [jclarke0000/MMM-MyScoreboard#9]
Hello,
I cloned this to my modules folder and then installed and restarted. I made sure to add it to the config file as well. Now it is stuck on loading on my magic mirror screen. Any help would be appreciated, thanks.

**Comment by tony1550** [comment]
I have the same problem, followed the instructions and when started MM it shows the scoreboard header but says Loading......, double checked everything but still nothing. Does anyone have any suggestions, thanks in advance

**Comment by jclarke0000** [comment]
Do you see any errors in the logs?  Also, I just released an update to fix the Sportsnet feed issue.  Maybe this fixes your problem as well?

**Comment by tony1550** [comment]
just reinstalled the module and still says loading.... I can see the header but that's it. When I launch MM it does not indicate any errors, where exactly would I look for the errors? Please advise.

**Comment by tony1550** [comment]
Still can't get this module to work properly, removed the directory cleared the cache, then reinstalled it, and still MM displays the header of the scoreboard and then just loading.....
any advice will be greatly appreciated

**Comment by rfowl** [comment]
I just did the install per the instructions and am also just getting the header with “Loading...”

**Comment by ghost** [comment]
I am getting the same. For me it seems to be when running in client/server. If I run it the traditional way it works. If I run it client server the client shows "loading..."

**Comment by ITCTE108** [comment]
I had that issue but when I restarted my raspberry pi it started working.

**Comment by radzuky** [comment]
I am stuck here too. Question is, for my config changes, do I modify the config.js in the MagicMirror/config directory or do I make all the changes to the MMM-Myscoreboard.js in MagicMirror/module/MMM-MyScoreboard directory?

If I have to only modify MMM-Myscorebaord.js, what should the config.js contain?

**Comment by Dz3015** [comment]
@jclarke0000 I'm on my first MM build and I was having the same issues.  After doing some digging and looking at your providers, it looks like the ESPN feeds may be working fine but the Sportsnet feeds may be whats broken.  I noticed that the NBA scores were provided by the ESPN API so I turned that league on and I got all the scores.  I'll update if I see/find anything else.

**Comment by bwiggs** [comment]
This started working for me once I realized I was just refreshing the frontend and had forgotten to restart MagicMirror so it would pickup on the new node_helper on the backend.

**Comment by Dz3015** [comment]
@bwiggs my apologies, I didn't update this.  This module is fine now for me.  It was being broken somehow by the GoogleMapsTraffic module.

**Comment by mdizzle777** [comment]
> @bwiggs my apologies, I didn't update this. This module is fine now for me. It was being broken somehow by the GoogleMapsTraffic module.

I had this same issue.  After disabling GoogleMapsTraffic, this module started working.  How can we have both working at the same time?

**Comment by Martin2K02** [comment]
I have the same problem, but I did it! To have both modules activated with GoogleMapsTraffic, you must go to the MMM-MyScoreboard.js file and then comment with // the line with "config.log". After that, It should now work with both modules.

I found the solution here: https://forum.magicmirror.builders/topic/10637/mmm-googlemapstraffic-has-impact-on-other-modules/5?lang=de&page=1 (It's german and a complete other module , but It also does work with the Scoreboard Module)

**Comment by Martin2K02** [comment]
> > @bwiggs my apologies, I didn't update this. This module is fine now for me. It was being broken somehow by the GoogleMapsTraffic module.
> 
> I had this same issue. After disabling GoogleMapsTraffic, this module started working. How can we have both working at the same time?

I have the same problem, but I did it! To have both modules activated with GoogleMapsTraffic, you must go to the MMM-MyScoreboard.js file and then comment (//) the line with "config.log". After that, It should now work with both modules.

I found the solution here: https://forum.magicmirror.builders/topic/10637/mmm-googlemapstraffic-has-impact-on-other-modules/5?lang=de&page=1 (It's german and a complete other module , but It also does work with the Scoreboard Module)
